name:         hdllib
version:      0.0.0
author:
- Fan Shupei <dymarkfan@outlook.com>
- Herman Bergwerf <hermanbergwerf@gmail.com>
description:  HDL processing library
homepage:     https://github.com/jisuan/hdllib
environment:
  sdk:        '>=1.8.0 <2.0.0'
dependencies:
  test:       '>=0.12.0'
